import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { 
  Brain, 
  TrendingUp, 
  Target, 
  Zap, 
  Users, 
  Award,
  CheckCircle,
  Code,
  BarChart3,
  Briefcase,
  Palette,
  Database,
  Shield,
  Sparkles,
  ArrowRight
} from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import GlassCard from '../common/GlassCard'
import PrimaryButton from '../common/PrimaryButton'

const roles = [
  { id: 'software-engineer', name: 'Software Engineer', icon: Code, description: 'Technical interviews, coding challenges, system design' },
  { id: 'data-scientist', name: 'Data Scientist', icon: BarChart3, description: 'ML algorithms, statistics, data analysis' },
  { id: 'product-manager', name: 'Product Manager', icon: Briefcase, description: 'Product strategy, prioritization, stakeholder management' },
  { id: 'designer', name: 'UX/UI Designer', icon: Palette, description: 'Design thinking, user research, portfolio reviews' },
  { id: 'data-engineer', name: 'Data Engineer', icon: Database, description: 'Data pipelines, ETL, infrastructure' },
  { id: 'security-engineer', name: 'Security Engineer', icon: Shield, description: 'Security protocols, threat analysis, compliance' },
  { id: 'marketing', name: 'Marketing Professional', icon: Users, description: 'Campaign strategy, analytics, brand management' },
  { id: 'sales', name: 'Sales Professional', icon: Target, description: 'Sales techniques, negotiation, client relations' },
  { id: 'hr', name: 'HR Professional', icon: Users, description: 'Talent acquisition, organizational behavior, HR strategy' },
]

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Questions',
    description: 'Get realistic interview questions generated by advanced AI, tailored to your role and experience level.'
  },
  {
    icon: Zap,
    title: 'Instant Feedback',
    description: 'Receive detailed, actionable feedback on your answers within seconds, helping you improve quickly.'
  },
  {
    icon: TrendingUp,
    title: 'Track Progress',
    description: 'Monitor your improvement over time with detailed analytics and performance metrics.'
  },
  {
    icon: Target,
    title: 'Role-Specific Practice',
    description: 'Practice interviews tailored to your specific role - from coding to product management.'
  },
  {
    icon: Users,
    title: 'Multiple Interview Types',
    description: 'Practice technical, behavioral, and system design interviews all in one platform.'
  },
  {
    icon: Award,
    title: 'Skill Assessment',
    description: 'Get comprehensive skill assessments with strengths and areas for improvement.'
  },
]

export default function Landing() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [selectedRole, setSelectedRole] = useState(null)

  const handleGetStarted = () => {
    if (user) {
      navigate('/dashboard')
    } else {
      navigate('/register')
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-cyan-50 to-indigo-50 relative overflow-hidden">
      {/* Animated Blob Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <motion.div
          animate={{
            x: [0, 100, 0],
            y: [0, 50, 0],
            scale: [1, 1.1, 1],
          }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: "easeInOut"
          }}
          className="absolute top-20 left-10 w-96 h-96 bg-cyan-400/20 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            x: [0, -80, 0],
            y: [0, -60, 0],
            scale: [1, 1.2, 1],
          }}
          transition={{
            duration: 25,
            repeat: Infinity,
            ease: "easeInOut",
            delay: 2
          }}
          className="absolute top-40 right-20 w-80 h-80 bg-blue-400/20 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            x: [0, 60, 0],
            y: [0, -40, 0],
            scale: [1, 1.15, 1],
          }}
          transition={{
            duration: 18,
            repeat: Infinity,
            ease: "easeInOut",
            delay: 4
          }}
          className="absolute bottom-20 left-1/3 w-72 h-72 bg-indigo-400/15 rounded-full blur-3xl"
        />
      </div>

      {/* Hero Section */}
      <section className="relative z-10 pt-32 pb-40 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="text-center"
          >
            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2, duration: 0.5 }}
              className="flex justify-center mb-8"
            >
              <GlassCard className="inline-flex items-center px-5 py-2.5 border-[#713600]/20">
                <Brain className="w-4 h-4 mr-2 text-[#C05800]" />
                <span className="text-sm font-semibold text-[#38240D] dark:text-white">AI-Powered Interview Preparation</span>
              </GlassCard>
            </motion.div>
            
            {/* Main Heading */}
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.6 }}
              className="text-5xl md:text-7xl lg:text-8xl font-extrabold text-[#38240D] dark:text-white mb-6 leading-tight tracking-tight"
            >
              Ace Your Next
              <br />
              <span className="text-[#C05800]">Job Interview</span>
            </motion.h1>
            
            {/* Subheading */}
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.6 }}
              className="text-xl md:text-2xl text-[#38240D]/80 dark:text-gray-300 mb-10 max-w-3xl mx-auto leading-relaxed font-medium"
            >
              The most advanced AI-powered interview preparation platform. Practice with realistic mock interviews, 
              get instant personalized feedback, and land your dream job—regardless of your role or industry.
            </motion.p>

            {/* CTAs */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.6 }}
              className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-16"
            >
              <PrimaryButton onClick={handleGetStarted}>
                Get Started Free
              </PrimaryButton>
              
              {!user && (
                <PrimaryButton onClick={() => navigate('/login')} variant="secondary">
                  Sign In
                </PrimaryButton>
              )}
            </motion.div>

            {/* Stats */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6, duration: 0.6 }}
              className="grid grid-cols-3 gap-8 max-w-2xl mx-auto"
            >
              {[
                { value: '10K+', label: 'Practice Sessions' },
                { value: '95%', label: 'Success Rate' },
                { value: '4.9/5', label: 'User Rating' }
              ].map((stat, idx) => (
                <GlassCard key={idx} hover={false} className="p-6">
                  <div className="text-3xl md:text-4xl font-bold text-[#C05800] mb-2">{stat.value}</div>
                  <div className="text-sm text-[#38240D]/70 dark:text-gray-400 font-medium">{stat.label}</div>
                </GlassCard>
              ))}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Role Selection Section */}
      <section className="relative z-10 py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <div className="flex justify-center mb-6">
              <GlassCard className="inline-flex items-center px-5 py-2.5 border-[#713600]/20">
                <Users className="w-4 h-4 mr-2 text-[#C05800]" />
                <span className="text-sm font-semibold text-[#38240D] dark:text-white">For Every Professional</span>
              </GlassCard>
            </div>
            
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-[#38240D] dark:text-white mb-6">
              Practice for <span className="text-[#C05800]">Your Role</span>
            </h2>
            <p className="text-xl text-[#38240D]/70 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed">
              Whether you're a developer, designer, manager, or any other professional—get personalized interview questions and feedback tailored to your career path
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {roles.map((role, index) => {
              const Icon = role.icon
              return (
                <motion.div
                  key={role.id}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ delay: index * 0.1, duration: 0.5 }}
                  whileHover={{ y: -8 }}
                  onClick={() => setSelectedRole(role.id)}
                >
                  <GlassCard
                    className={`
                      p-6 cursor-pointer
                      ${selectedRole === role.id 
                        ? 'border-[#C05800]/40 bg-white/60 dark:bg-white/30 shadow-2xl' 
                        : 'border-white/30'
                      }
                    `}
                  >
                    <div className={`
                      w-14 h-14 rounded-xl flex items-center justify-center mb-4
                      ${selectedRole === role.id 
                        ? 'bg-[#C05800] shadow-lg shadow-[#C05800]/30' 
                        : 'bg-[#713600]/20 dark:bg-[#713600]/30'
                      }
                      transition-all duration-300
                    `}>
                      <Icon className={`w-7 h-7 ${selectedRole === role.id ? 'text-white' : 'text-[#713600] dark:text-[#C05800]'}`} />
                    </div>
                    <h3 className="text-xl font-bold text-[#38240D] dark:text-white mb-2">{role.name}</h3>
                    <p className="text-[#38240D]/70 dark:text-gray-300 text-sm leading-relaxed">{role.description}</p>
                    {selectedRole === role.id && (
                      <motion.div
                        initial={{ scale: 0, rotate: -180 }}
                        animate={{ scale: 1, rotate: 0 }}
                        className="absolute top-4 right-4"
                      >
                        <div className="w-6 h-6 bg-[#C05800] rounded-full flex items-center justify-center shadow-lg">
                          <CheckCircle className="w-4 h-4 text-white" />
                        </div>
                      </motion.div>
                    )}
                  </GlassCard>
                </motion.div>
              )
            })}
          </div>

          {selectedRole && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mt-12 text-center"
            >
              <PrimaryButton onClick={handleGetStarted}>
                Start {roles.find(r => r.id === selectedRole)?.name} Interview
              </PrimaryButton>
            </motion.div>
          )}
        </div>
      </section>

      {/* Features Section */}
      <section className="relative z-10 py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-[#38240D] dark:text-white mb-6">
              Everything You Need to Succeed
            </h2>
            <p className="text-xl text-[#38240D]/70 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed">
              Powerful features designed to help you prepare and excel in your interviews
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => {
              const Icon = feature.icon
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ delay: index * 0.1, duration: 0.5 }}
                  whileHover={{ y: -8 }}
                >
                  <GlassCard className="p-8 h-full">
                    <div className="w-14 h-14 bg-[#C05800]/10 dark:bg-[#C05800]/20 rounded-xl flex items-center justify-center mb-6 group-hover:bg-[#C05800]/20 dark:group-hover:bg-[#C05800]/30 transition-colors duration-300">
                      <Icon className="w-7 h-7 text-[#C05800]" />
                    </div>
                    <h3 className="text-xl font-bold text-[#38240D] dark:text-white mb-3">{feature.title}</h3>
                    <p className="text-[#38240D]/70 dark:text-gray-300 leading-relaxed">{feature.description}</p>
                  </GlassCard>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      {/* Skill Assessment CTA Section */}
      <section className="relative z-10 py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="text-center"
          >
            <GlassCard className="p-12 md:p-16 border-cyan-500/30 bg-gradient-to-br from-cyan-50/50 to-blue-50/50 dark:from-cyan-900/20 dark:to-blue-900/20">
              <motion.div
                animate={{ rotate: [0, 10, -10, 0] }}
                transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
                className="inline-block mb-6"
              >
                <Award className="w-12 h-12 text-cyan-600 dark:text-cyan-400" />
              </motion.div>
              
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold bg-gradient-to-r from-cyan-600 to-blue-600 bg-clip-text text-transparent mb-6">
                Test Your Skills Now
              </h2>
              <p className="text-xl md:text-2xl text-[#38240D]/80 dark:text-gray-300 mb-10 max-w-2xl mx-auto leading-relaxed">
                Take our interactive skill assessment for any role. Get instant feedback, identify strengths, and discover areas for improvement—no sign-up required!
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <PrimaryButton 
                  onClick={() => navigate('/skill-assessment')}
                  className="bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600"
                >
                  Start Skill Assessment
                  <ArrowRight className="w-5 h-5 ml-2" />
                </PrimaryButton>
              </div>
            </GlassCard>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="relative z-10 py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="text-center"
          >
            <GlassCard className="p-12 md:p-16 border-[#713600]/20 bg-white/50 dark:bg-white/25">
              <motion.div
                animate={{ rotate: [0, 10, -10, 0] }}
                transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
                className="inline-block mb-6"
              >
                <Sparkles className="w-12 h-12 text-[#C05800]" />
              </motion.div>
              
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-[#38240D] dark:text-white mb-6">
                Ready to Ace Your Interview?
              </h2>
              <p className="text-xl md:text-2xl text-[#38240D]/80 dark:text-gray-300 mb-10 max-w-2xl mx-auto leading-relaxed">
                Join thousands of professionals across all industries who have improved their interview skills and landed their dream jobs with AI Interview Coach
              </p>
              <PrimaryButton onClick={handleGetStarted}>
                Start Practicing Now
              </PrimaryButton>
            </GlassCard>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
